language: node_js
sudo: false

node_js:
  - '6.10.2'

addons:
  jwt:
    # SAUCE_ACCESS_KEY<=secret for FIREBASE_ACCESS_TOKEN to work around travis-ci/travis-ci#7223, unencrypted value in valentine as FIREBASE_ACCESS_TOKEN>
    # we alias FIREBASE_ACCESS_TOKEN to $SAUCE_ACCESS_KEY in env.sh and set the SAUCE_ACCESS_KEY there
    - secure: "kRjLueTSiHbqHD6HVUBDhLv05Ehwb+UPGBdxdfHzMndxKaj58kC3o/bHcsWWY4eQXNu6KSSFLHzdj5eoujfBPk+9sX9ZHZbWa9u14ekm3fhaHDGcqQwaitIU6f5L3yF9Zhgz8wpuDSDmUY9LNHhEgBto7YPuJDZRv4DUvqC4Q9hin8y7L+HJE6lO0nxE3t/Yq/pUzaH2rxoEe6fq0sh5E+IsTvBjqw20gjhjYlIZkICL/pU5YYzk6jCh/8PYcZ1NLCTFA4qWoymg8ZLqLsdk8nyrPIsrHqbqF0TaN0UUERc2gfecA4fnQDXK3gAZWM8nlfn7aEUEy1CyKZuMsJbwy8hF5/HzVrZCfZs1/6FhJ1MVcLbr7o8xUDs2n3TIjpxLqUOvnrwTriV2b50VJBtd8vlJmZuNcIXX7n1EBsGzuDfEn+wCiw9pbrJBLYDv4Jtnwnwcvs3ahjLGzs3ogm6UgAuUVYzIHsy8rkCItpQSl9uQid+Gd6BKgmxc6n5yWb9cY8hafi9wkzz5ZebpT44H25eQltsnBTvm8Pr4Cj22MNXWfIl/DWCkn2gvE6vJLrqMaW479ozEFJY7UhgIeK0Y7IUT2FZv4KGjMALUkmiprHPCLbDeZUyLJ/fkMGHbdvVsy4Zj7Bs35diRxAwQoLxKKtbrdUDiJcVwhP52Wuc+ZSg="

branches:
  only:
  - master

env:
  global:
  - LOGS_DIR=/tmp/uniprank-ngxfileuploader-build/logs
  - SAUCE_USERNAME=Delomi
  - BROWSER_STACK_USERNAME=denfie83@gmail.com
  - BROWSER_STACK_ACCESS_KEY=1K5pAkQmr6u3yBa8qYsA
  - BROWSER_PROVIDER_READY_FILE=/tmp/uniprank-ngxfileuploader-build/readyfile
  - BROWSER_PROVIDER_ERROR_FILE=/tmp/uniprank-ngxfileuploader-build/errorfile

  matrix:
    # Order: a slower build first, so that we don't occupy an idle travis worker waiting for others to complete.
    - MODE=lint
    - MODE=aot
    - MODE=closure-compiler
    - MODE=payload
    - MODE=e2e
    - MODE=saucelabs_required
    - MODE=browserstack_required

matrix:
  fast_finish: true
  allow_failures:
  - env: "MODE=saucelabs_optional"
  - env: "MODE=browserstack_optional"

before_install:
  - source ./scripts/ci/env.sh

install:
  - npm install

before_script:
  - mkdir -p $LOGS_DIR

script:
  - ./scripts/ci/build-and-test.sh

after_success:
  - ./scripts/ci/after-success.sh

cache:
  directories:
    - node_modules
    - $HOME/.pub-cache